export const M3_SCHEDULE_CONTRACT_ID = 'M3_CONTRACT_V1';
export const M3_SCHEDULE_CONTRACT_VERSION = '1.0.0';

export const CANONICAL_SCHEDULE_REASON_CODES = [
  'TEACHER_TIME_OVERLAP',
  'STUDENT_GROUP_TIME_OVERLAP',
  'ROOM_TIME_OVERLAP',
  'TIMESLOT_INACTIVE',
  'TEACHER_INACTIVE',
  'STUDENT_GROUP_INACTIVE',
  'TEACHER_BRANCH_ASSIGNMENT_MISSING',
  'TEACHER_COURSE_MISMATCH',
  'TENANT_REFERENCE_MISMATCH',
  'BRANCH_REFERENCE_MISMATCH',
  'PUBLISHED_SCHEDULE_IMMUTABLE',
  'SCHEDULE_EMPTY',
  'SCHEDULE_VALIDATION_STALE',
  'SCHEDULE_HARD_CONFLICTS_PRESENT',
  'PUBLISHED_SCHEDULE_PERIOD_CONFLICT',
  'SCHEDULE_VERSION_MISMATCH',
  'SCHEDULE_VERSION_REQUIRED',
] as const;

export type CanonicalScheduleReasonCode = typeof CANONICAL_SCHEDULE_REASON_CODES[number];
