import { AppDataSource } from '../data-source';

export const PERMISSION_SEED = [
  { code: 'dashboard:read', description: 'dashboard:read' },
  { code: 'dashboard:operations_summary:read', description: 'dashboard:operations_summary:read' },
  { code: 'dashboard:teacher_own_summary:read', description: 'dashboard:teacher_own_summary:read' },
  { code: 'daily_operations:read', description: 'daily_operations:read' },
  { code: 'daily_operations:own:read', description: 'daily_operations:own:read' },
  { code: 'daily_operations:create', description: 'daily_operations:create' },
  { code: 'daily_operations:update', description: 'daily_operations:update' },
  { code: 'schedule:read', description: 'schedule:read' },
  { code: 'schedule:own:read', description: 'schedule:own:read' },
  { code: 'schedule:draft:create', description: 'schedule:draft:create' },
  { code: 'schedule:draft:update', description: 'schedule:draft:update' },
  { code: 'schedule:validate', description: 'schedule:validate' },
  { code: 'schedule:optimize', description: 'schedule:optimize' },
  { code: 'schedule:publish', description: 'schedule:publish' },
  { code: 'schedule:conflict:read', description: 'schedule:conflict:read' },
  { code: 'schedule:assignment:update', description: 'schedule:assignment:update' },
  { code: 'leave:read', description: 'leave:read' },
  { code: 'leave:own:read', description: 'leave:own:read' },
  { code: 'leave:create', description: 'leave:create' },
  { code: 'leave:impact:read', description: 'leave:impact:read' },
  { code: 'leave:approve', description: 'leave:approve' },
  { code: 'leave:reject', description: 'leave:reject' },
  { code: 'attendance:generate', description: 'attendance:generate' },
  { code: 'attendance:read', description: 'attendance:read' },
  { code: 'attendance:own:read', description: 'attendance:own:read' },
  { code: 'attendance:submit', description: 'attendance:submit' },
  { code: 'attendance:own:submit', description: 'attendance:own:submit' },
  { code: 'attendance:record:update', description: 'attendance:record:update' },
  { code: 'attendance:update', description: 'attendance:update' },
  { code: 'attendance:lock', description: 'attendance:lock' },
  { code: 'attendance:unlock', description: 'attendance:unlock' },
  { code: 'attendance:missing:read', description: 'attendance:missing:read' },
  { code: 'attendance:absence:read', description: 'attendance:absence:read' },
  { code: 'attendance:report:read', description: 'attendance:report:read' },
  { code: 'parent_notification:draft:create', description: 'parent_notification:draft:create' },
  { code: 'parent_notification:read', description: 'parent_notification:read' },
  { code: 'parent_notification:approve', description: 'parent_notification:approve' },
  { code: 'parent_notification:send', description: 'parent_notification:send' },
  { code: 'parent_notification:failure:read', description: 'parent_notification:failure:read' },
  { code: 'parent_notification:history:read', description: 'parent_notification:history:read' },
  { code: 'message_template:read', description: 'message_template:read' },
  { code: 'message_template:create', description: 'message_template:create' },
  { code: 'message_template:update', description: 'message_template:update' },
  { code: 'message_template:activate', description: 'message_template:activate' },
  { code: 'message_template:deactivate', description: 'message_template:deactivate' },
  { code: 'user:read', description: 'user:read' },
  { code: 'user:create', description: 'user:create' },
  { code: 'user:update', description: 'user:update' },
  { code: 'user:deactivate', description: 'user:deactivate' },
  { code: 'user:invite', description: 'user:invite' },
  { code: 'user:membership:read', description: 'user:membership:read' },
  { code: 'user:membership:update', description: 'user:membership:update' },
  { code: 'user:profile:read', description: 'user:profile:read' },
  { code: 'role:read', description: 'role:read' },
  { code: 'role:create', description: 'role:create' },
  { code: 'role:update', description: 'role:update' },
  { code: 'role:assign', description: 'role:assign' },
  { code: 'role:remove', description: 'role:remove' },
  { code: 'role:permission:read', description: 'role:permission:read' },
  { code: 'role:permission:update', description: 'role:permission:update' },
  { code: 'role:audit:read', description: 'role:audit:read' },
  { code: 'audit_log:read', description: 'audit_log:read' },
  { code: 'audit_log:operations:read', description: 'audit_log:operations:read' },
  { code: 'audit_log:security:read', description: 'audit_log:security:read' },
  { code: 'teacher:read', description: 'teacher:read' },
  { code: 'teacher:own:read', description: 'teacher:own:read' },
  { code: 'teacher:create', description: 'teacher:create' },
  { code: 'teacher:update', description: 'teacher:update' },
  { code: 'teacher:deactivate', description: 'teacher:deactivate' },
  { code: 'teacher:availability:read', description: 'teacher:availability:read' },
  { code: 'teacher:availability:update', description: 'teacher:availability:update' },
  { code: 'teacher:assignment:read', description: 'teacher:assignment:read' },
  { code: 'teacher:assignment:update', description: 'teacher:assignment:update' },
  { code: 'teacher:schedule:read', description: 'teacher:schedule:read' },
  { code: 'student:read', description: 'student:read' },
  { code: 'student:detail:read', description: 'student:detail:read' },
  { code: 'student:group_students:read', description: 'student:group_students:read' },
  { code: 'student:create', description: 'student:create' },
  { code: 'student:update', description: 'student:update' },
  { code: 'student:deactivate', description: 'student:deactivate' },
  { code: 'student:parent_contact:read', description: 'student:parent_contact:read' },
  { code: 'student:kvkk:read', description: 'student:kvkk:read' },
  { code: 'student:enrollment:read', description: 'student:enrollment:read' },
  { code: 'student:enrollment:update', description: 'student:enrollment:update' },
  { code: 'student:attendance:read', description: 'student:attendance:read' },
  { code: 'course:read', description: 'course:read' },
  { code: 'course:create', description: 'course:create' },
  { code: 'course:update', description: 'course:update' },
  { code: 'course:delete', description: 'course:delete' },
  { code: 'course:assign_teacher', description: 'course:assign_teacher' },
  { code: 'course:archive', description: 'course:archive' },
  { code: 'course:schedule:read', description: 'course:schedule:read' },
  { code: 'room:read', description: 'room:read' },
  { code: 'room:create', description: 'room:create' },
  { code: 'room:update', description: 'room:update' },
  { code: 'room:delete', description: 'room:delete' },
  { code: 'room:availability:read', description: 'room:availability:read' },
  { code: 'room:availability:update', description: 'room:availability:update' },
  { code: 'room:schedule:read', description: 'room:schedule:read' },
  { code: 'time_slot:read', description: 'time_slot:read' },
  { code: 'time_slot:create', description: 'time_slot:create' },
  { code: 'time_slot:update', description: 'time_slot:update' },
  { code: 'time_slot:delete', description: 'time_slot:delete' },
  { code: 'time_slot:calendar:read', description: 'time_slot:calendar:read' },
  { code: 'tenant:read', description: 'tenant:read' },
  { code: 'tenant:update', description: 'tenant:update' },
  { code: 'tenant:settings:read', description: 'tenant:settings:read' },
  { code: 'tenant:settings:update', description: 'tenant:settings:update' },
  { code: 'tenant:branch:read', description: 'tenant:branch:read' },
  { code: 'tenant:branch:create', description: 'tenant:branch:create' },
  { code: 'tenant:branch:update', description: 'tenant:branch:update' },
  { code: 'tenant:branch:deactivate', description: 'tenant:branch:deactivate' },
  { code: 'tenant:member:read', description: 'tenant:member:read' },
  { code: 'tenant:member:update', description: 'tenant:member:update' },
  { code: 'tenant:billing:read', description: 'tenant:billing:read' },

  'dashboard:read',
  'dashboard:operations_summary:read',
  'dashboard:teacher_own_summary:read',
  'dashboard:kpi:read',
  'dashboard:alerts:read',
  'daily_operations:read',
  'daily_operations:own:read',
  'daily_operations:missing_attendance:read',
  'daily_operations:pending_notifications:read',
  'daily_operations:close',
  'daily_operations:report:read',
  'schedule:draft:read',
  'schedule:draft:create',
  'schedule:draft:update',
  'schedule:draft:delete',
  'schedule:validate',
  'schedule:optimize',
  'schedule:publish',
  'schedule:published:read',
  'schedule:own:read',
  'schedule:conflicts:read',
  'leave:read',
  'leave:own:read',
  'leave:create',
  'leave:update',
  'leave:impact:analyze',
  'leave:substitution:read',
  'leave:approve',
  'leave:reject',
  'leave:cancel',
  'attendance:generate',
  'attendance:read',
  'attendance:own:read',
  'attendance:session:read',
  'attendance:submit',
  'attendance:record:update',
  'attendance:lock',
  'attendance:unlock',
  'attendance:missing:read',
  'attendance:absence:read',
  'parent_notification:draft',
  'parent_notification:read',
  'parent_notification:detail:read',
  'parent_notification:approve',
  'parent_notification:send',
  'parent_notification:bulk_send',
  'parent_notification:cancel',
  'parent_notification:failure:read',
  'message_template:read',
  'message_template:create',
  'message_template:update',
  'message_template:delete',
  'message_template:activate',
  'message_template:deactivate',
  'user:read',
  'user:detail:read',
  'user:create',
  'user:update',
  'user:deactivate',
  'user:session:revoke',
  'user:own_profile:read',
  'user:own_profile:update',
  'role:read',
  'role:assign',
  'role:remove',
  'role:permission:read',
  'role:system_seed:run',
  'audit_log:read',
  'audit_log:operations:read',
  'audit_log:security:read',
  'audit_log:export',
  'audit_log:entity_history:read',
  'teacher:read',
  'teacher:detail:read',
  'teacher:create',
  'teacher:update',
  'teacher:deactivate',
  'teacher:own:read',
  'teacher:availability:read',
  'teacher:availability:update',
  'teacher:branch_assignment:update',
  'student:read',
  'student:detail:read',
  'student:create',
  'student:update',
  'student:delete',
  'student:group_students:read',
  'student:parent_contact:read',
  'student:kvkk:read',
  'student:kvkk:update',
  'course:read',
  'course:detail:read',
  'course:create',
  'course:update',
  'course:delete',
  'course:branch_requirement:update',
  'room:read',
  'room:detail:read',
  'room:create',
  'room:update',
  'room:delete',
  'room:availability:read',
  'time_slot:read',
  'time_slot:create',
  'time_slot:update',
  'time_slot:delete',
  'time_slot:calendar_rule:update',
  'tenant:read',
  'tenant:update',
  'tenant:settings:read',
  'tenant:settings:update',
  'tenant:branch:read',
  'tenant:branch:create',
  'tenant:branch:update',
  'tenant:branch:deactivate',
] as const;

export const ROLE_PERMISSION_SEED = {
  tenant_admin: PERMISSION_SEED.map((permission) => permission.code),
  operations_manager: [
    'attendance:absence:read',
    'attendance:generate',
    'attendance:lock',
    'attendance:missing:read',
    'attendance:own:read',
    'attendance:own:submit',
    'attendance:read',
    'attendance:record:update',
    'attendance:report:read',
    'attendance:submit',
    'attendance:update',
    'audit_log:operations:read',
    'course:archive',
    'course:assign_teacher',
    'course:create',
    'course:delete',
    'course:read',
    'course:schedule:read',
    'course:update',
    'daily_operations:create',
    'daily_operations:own:read',
    'daily_operations:read',
    'daily_operations:update',
    'dashboard:operations_summary:read',
    'dashboard:read',
    'dashboard:teacher_own_summary:read',
    'leave:approve',
    'leave:create',
    'leave:impact:read',
    'leave:own:read',
    'leave:read',
    'leave:reject',
    'message_template:activate',
    'message_template:create',
    'message_template:deactivate',
    'message_template:read',
    'message_template:update',
    'parent_notification:approve',
    'parent_notification:draft:create',
    'parent_notification:failure:read',
    'parent_notification:history:read',
    'parent_notification:read',
    'parent_notification:send',
    'room:availability:read',
    'room:availability:update',
    'room:create',
    'room:delete',
    'room:read',
    'room:schedule:read',
    'room:update',
    'schedule:assignment:update',
    'schedule:conflict:read',
    'schedule:draft:create',
    'schedule:draft:update',
    'schedule:optimize',
    'schedule:own:read',
    'schedule:publish',
    'schedule:read',
    'schedule:validate',
    'student:attendance:read',
    'student:create',
    'student:deactivate',
    'student:enrollment:read',
    'student:enrollment:update',
    'student:group_students:read',
    'student:read',
    'student:update',
    'teacher:assignment:read',
    'teacher:assignment:update',
    'teacher:availability:read',
    'teacher:availability:update',
    'teacher:create',
    'teacher:deactivate',
    'teacher:own:read',
    'teacher:read',
    'teacher:schedule:read',
    'teacher:update',
    'time_slot:calendar:read',
    'time_slot:create',
    'time_slot:delete',
    'time_slot:read',
    'time_slot:update',
  ],
  teacher: [
    'dashboard:teacher_own_summary:read',
    'daily_operations:own:read',
    'schedule:own:read',
    'leave:create',
    'leave:own:read',
    'attendance:own:read',
    'attendance:own:submit',
    'attendance:record:update',
    'student:group_students:read',
    'teacher:own:read',
    'teacher:availability:read',
    'course:read',
    'room:read',
    'time_slot:read',
  ],
} as const;

export async function seedPermissions(): Promise<void> {
  const ownsConnection = !AppDataSource.isInitialized;
  const ds = AppDataSource.isInitialized ? AppDataSource : await AppDataSource.initialize();
  try {
    await ds.transaction(async (manager) => {
      const tenantSlug = process.env.SEED_TENANT_SLUG ?? 'system-seed';
      const tenantName = process.env.SEED_TENANT_NAME ?? 'System Seed Tenant';
      const tenantRows = await manager.query(
        `INSERT INTO tenants (name, slug) VALUES ($1, $2) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, updated_at = now() RETURNING id`,
        [tenantName, tenantSlug],
      );
      const tenantId = tenantRows[0].id;
      for (const permission of PERMISSION_SEED) {
        await manager.query(
          `INSERT INTO permissions (code, description) VALUES ($1, $2) ON CONFLICT (code) DO UPDATE SET description = EXCLUDED.description`,
          [permission.code, permission.description],
        );
      }
      for (const roleCode of Object.keys(ROLE_PERMISSION_SEED)) {
        await manager.query(
          `INSERT INTO roles (tenant_id, name, description, is_system_role) VALUES ($1, $2, $3, true) ON CONFLICT (tenant_id, name) DO UPDATE SET description = EXCLUDED.description, is_system_role = true, updated_at = now()`,
          [tenantId, roleCode, `${roleCode} default role`],
        );
      }
      for (const [roleCode, permissionCodes] of Object.entries(ROLE_PERMISSION_SEED)) {
        await manager.query(
          `INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.tenant_id = $1 AND r.name = $2 AND p.code = ANY($3::varchar[]) ON CONFLICT DO NOTHING`,
          [tenantId, roleCode, permissionCodes],
        );
      }
    });
    console.log(`Permissions upserted: ${PERMISSION_SEED.length}`);
    console.log('Roles ensured: 3');
    console.log(`tenant_admin permissions assigned: ${ROLE_PERMISSION_SEED.tenant_admin.length}`);
    console.log(`operations_manager permissions assigned: ${ROLE_PERMISSION_SEED.operations_manager.length}`);
    console.log(`teacher permissions assigned: ${ROLE_PERMISSION_SEED.teacher.length}`);
    console.log('Permission seed completed');
  } finally {
    if (ownsConnection && ds.isInitialized) await ds.destroy();
  }
}

if (require.main === module) {
  seedPermissions().catch((error) => {
    console.error(`Permission seed failed: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  });
}
