export { ROLE_PERMISSION_SEED as ROLE_SEED } from './permissions.seed';

import { PERMISSION_SEED } from './permissions.seed';

export const ROLE_SEED = [
  { code: 'tenant_admin', permissions: [...PERMISSION_SEED] },
  { code: 'operations_manager', permissions: ['dashboard:read', 'dashboard:operations_summary:read', 'dashboard:alerts:read', 'daily_operations:read', 'daily_operations:missing_attendance:read', 'daily_operations:pending_notifications:read', 'daily_operations:close', 'daily_operations:report:read', 'schedule:draft:read', 'schedule:draft:create', 'schedule:draft:update', 'schedule:draft:delete', 'schedule:validate', 'schedule:optimize', 'schedule:publish', 'schedule:published:read', 'schedule:conflicts:read', 'leave:read', 'leave:create', 'leave:update', 'leave:impact:analyze', 'leave:substitution:read', 'leave:approve', 'leave:reject', 'leave:cancel', 'attendance:generate', 'attendance:read', 'attendance:session:read', 'attendance:submit', 'attendance:record:update', 'attendance:lock', 'attendance:missing:read', 'attendance:absence:read', 'parent_notification:draft', 'parent_notification:read', 'parent_notification:detail:read', 'parent_notification:approve', 'parent_notification:send', 'parent_notification:bulk_send', 'parent_notification:cancel', 'parent_notification:failure:read', 'message_template:read', 'message_template:create', 'message_template:update', 'message_template:activate', 'message_template:deactivate', 'user:own_profile:read', 'user:own_profile:update', 'audit_log:operations:read', 'audit_log:entity_history:read', 'teacher:read', 'teacher:detail:read', 'teacher:create', 'teacher:update', 'teacher:availability:read', 'teacher:availability:update', 'teacher:branch_assignment:update', 'student:read', 'student:detail:read', 'student:create', 'student:update', 'student:group_students:read', 'student:parent_contact:read', 'student:kvkk:read', 'student:kvkk:update', 'course:read', 'course:detail:read', 'course:create', 'course:update', 'course:branch_requirement:update', 'room:read', 'room:detail:read', 'room:create', 'room:update', 'room:availability:read', 'time_slot:read', 'time_slot:create', 'time_slot:update', 'time_slot:calendar_rule:update', 'tenant:branch:read'] },
  { code: 'teacher', permissions: ['dashboard:teacher_own_summary:read', 'daily_operations:own:read', 'schedule:own:read', 'leave:create', 'leave:own:read', 'leave:update', 'leave:impact:analyze', 'leave:cancel', 'attendance:own:read', 'attendance:session:read', 'attendance:submit', 'attendance:record:update', 'attendance:absence:read', 'student:group_students:read', 'teacher:own:read', 'teacher:availability:read', 'teacher:availability:update', 'course:read', 'course:detail:read', 'room:read', 'time_slot:read', 'user:own_profile:read', 'user:own_profile:update'] },
] as const;
