export const OPERATIONS_SKELETON_ACCEPTANCE = {
  apiBinding: 'not_connected',
  permissionCatalogBinding: 'pending',
  hardCodedPermissionKeys: false,
  runtimeRouteGuardChanged: false,
  studentDataRendered: false,
  parentContactRendered: false,
  notificationPayloadRendered: false,
  counselingNoteRendered: false,
  rawPayloadRendered: false,
  tenantIdRendered: false,
  runtimeMutationsEnabled: false,
  scheduleConsumesTimeSlotRuntime: false,
  m3ContractAlignmentOnly: true,
  m3ContractSource: 'Issue #40 contract draft',
  scheduleDraftListDescriptorPresent: true,
  scheduleWeeklyGridDescriptorPresent: true,
  scheduleEventEditorModalDescriptorPresent: true,
  scheduleConflictPanelDescriptorPresent: true,
  scheduleValidationResultDescriptorPresent: true,
  schedulePublishConfirmationDescriptorPresent: true,
  scheduleStaleVersionWarningDescriptorPresent: true,
  scheduleForbiddenStateDescriptorPresent: true,
  scheduleLifecycle: ['draft', 'published', 'unpublished'],
  scheduleValidationLifecycle: ['not_validated', 'valid', 'invalid', 'stale'],
  publishedScheduleImmutable: true,
  publishRequiresCurrentFullValidation: true,
  publishRequiresHardConflictCountZero: true,
  affectedValidationEnablesPublish: false,
  staleVersionAutomaticRetry: false,
  teacherDraftDiscoveryEnabled: false,
  teacherOwnPublishedReadPlaceholder: true,
  viewerDraftDiscoveryEnabled: false,
  viewerPublishedReadOnlyPlaceholder: true,
} as const;
