export const OPERATIONS_SKELETON_ACCEPTANCE = {
  apiBinding: 'not_connected',
  permissionCatalogBinding: 'pending',
  hardCodedPermissionKeys: false,
  runtimeRouteGuardChanged: false,
  studentDataRendered: false,
  parentContactRendered: false,
  notificationPayloadRendered: false,
  counselingNoteRendered: false,
  rawPayloadRendered: false,
  tenantIdRendered: false,
  runtimeMutationsEnabled: false,
  scheduleConsumesTimeSlotRuntime: false,
  m3ContractAlignmentOnly: true,
  m3ContractSource: 'Issue #40 contract draft',
  scheduleDraftListDescriptorPresent: true,
  scheduleWeeklyGridDescriptorPresent: true,
  scheduleEventEditorModalDescriptorPresent: true,
  scheduleConflictPanelDescriptorPresent: true,
  scheduleValidationResultDescriptorPresent: true,
  schedulePublishConfirmationDescriptorPresent: true,
  scheduleStaleVersionWarningDescriptorPresent: true,
  scheduleForbiddenStateDescriptorPresent: true,
  scheduleLifecycle: ['draft', 'published', 'unpublished'],
  scheduleValidationLifecycle: ['not_validated', 'valid', 'invalid', 'stale'],
  publishedScheduleImmutable: true,
  unpublishedScheduleImmutable: true,
  publishRequiresCurrentFullValidation: true,
  publishRequiresHardConflictCountZero: true,
  affectedValidationEnablesPublish: false,
  staleVersionAutomaticRetry: false,
  teacherDraftDiscoveryEnabled: false,
  teacherDraftGridVisible: false,
  teacherOwnPublishedReadPlaceholder: true,
  teacherPublishedProjection: 'own_events_only',
  viewerDraftDiscoveryEnabled: false,
  viewerDraftGridVisible: false,
  viewerPublishedReadOnlyPlaceholder: true,
  viewerPublishedProjection: 'contract_read_only',
  managementDraftGridSeparatedFromPublishedGrid: true,
  publishBlockReasonCodes: [
    'SCHEDULE_EMPTY',
    'SCHEDULE_VALIDATION_STALE',
    'SCHEDULE_HARD_CONFLICTS_PRESENT',
    'PUBLISHED_SCHEDULE_PERIOD_CONFLICT',
    'SCHEDULE_VERSION_MISMATCH',
  ],
  publishBlockReasonsCollapsedToScheduleEmpty: false,
} as const;
