import type { OperationsModule } from './operations.routes';
import type { OperationsUiState, ScheduleContractUiState } from './operations.states';

export type OperationsComponentDescriptor = {
  name: string;
  module: OperationsModule | 'shared';
  route: string;
  stateCoverage: readonly OperationsUiState[];
  contractStateCoverage?: readonly ScheduleContractUiState[];
  displays: readonly string[];
  doesNotDisplay: readonly string[];
  contractDependencies?: readonly string[];
  roleBoundaryNote?: string;
  apiBinding: 'not_connected';
  permissionBinding: 'pending_catalog';
  interactionEnabled: false;
  submitEnabled: false;
  runtimeComponent: false;
};

const OPERATIONS_SAFE_DISPLAY_FIELDS = [
  'page title',
  'contract notice',
  'permission dependency notice',
  'disabled action placeholder',
  'state label',
] as const;

export const OPERATIONS_FUTURE_RENDER_BLOCKLIST = [
  'student name',
  'student identity number',
  'student roster',
  'student note',
  'parent phone',
  'parent email',
  'guardian contact',
  'notification payload',
  'message body',
  'counseling note',
  'tenant id',
  'raw request payload',
  'raw response payload',
  'cross-tenant existence signal',
  'authorization header',
  'token',
  'credential',
] as const;

const SCHEDULE_CONTRACT_DEPENDENCIES = [
  'M3 Schedule contract draft in Issue #40',
  'Permission Catalog capability mapping',
  '403 and own-scope error mapping',
  'ETag response and If-Match mutation contract',
  'full hard-conflict validation result contract',
  'publish gate and immutable published lifecycle',
  'Branch Course Room TimeSlot Teacher StudentGroup reference contracts',
] as const;

export const OPERATIONS_COMPONENT_SKELETONS: readonly OperationsComponentDescriptor[] = [
  {
    name: 'DailyOperationPageSkeleton',
    module: 'daily_operation',
    route: '/app/today',
    stateCoverage: ['loading', 'empty', 'error', 'forbidden', 'contract_pending'],
    displays: ['daily summary placeholders', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: ['published schedule summary contract', 'daily operation API contract'],
    roleBoundaryNote: 'Tenant Admin and Operations Manager management placeholder; Teacher own-read; Viewer read-only.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'TodaySchedulePanelSkeleton',
    module: 'daily_operation',
    route: '/app/today',
    stateCoverage: ['loading', 'empty', 'error', 'forbidden', 'contract_pending'],
    displays: ['published schedule count placeholder', 'time block placeholder', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: ['published schedule projection contract'],
    roleBoundaryNote: 'Teacher projection must remain own-read and cannot expose draft or other-teacher schedule existence.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'LeaveImpactPlaceholder',
    module: 'daily_operation',
    route: '/app/today',
    stateCoverage: ['empty', 'error', 'forbidden', 'contract_pending'],
    displays: ['leave-impact contract notice', 'replacement-teacher placeholder', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: ['leave impact contract outside M3 Schedule binding'],
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'DailyClosurePanelSkeleton',
    module: 'daily_operation',
    route: '/app/today',
    stateCoverage: ['empty', 'error', 'forbidden', 'contract_pending'],
    displays: ['closure checklist placeholder', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: ['daily closure API contract'],
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'SchedulePageSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['loading', 'empty', 'error', 'forbidden', 'contract_pending'],
    contractStateCoverage: ['draft_list_ready', 'weekly_grid_ready', 'published_read_only'],
    displays: ['schedule shell placeholder', 'lifecycle status placeholder', 'version placeholder', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: SCHEDULE_CONTRACT_DEPENDENCIES,
    roleBoundaryNote: 'Management placeholders may see draft surfaces; Teacher own-events and Viewer contract read-only projections use only published_read_only.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'ScheduleDraftListSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['loading', 'empty', 'error', 'forbidden', 'contract_pending'],
    contractStateCoverage: ['draft_list_ready'],
    displays: [
      'draft name placeholder',
      'effective date range placeholder',
      'event count placeholder',
      'validation status placeholder',
      'version placeholder',
      ...OPERATIONS_SAFE_DISPLAY_FIELDS,
    ],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: SCHEDULE_CONTRACT_DEPENDENCIES,
    roleBoundaryNote: 'Visible only to Tenant Admin and Operations Manager placeholders; Teacher and Viewer draft discovery remains hidden.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'ScheduleWeeklyGridSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['loading', 'empty', 'error', 'forbidden', 'contract_pending'],
    contractStateCoverage: ['weekly_grid_ready', 'published_read_only'],
    displays: [
      'day columns placeholder',
      'TimeSlot row placeholder',
      'teacher display-name placeholder',
      'StudentGroup summary placeholder',
      'Course and Room label placeholder',
      ...OPERATIONS_SAFE_DISPLAY_FIELDS,
    ],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: SCHEDULE_CONTRACT_DEPENDENCIES,
    roleBoundaryNote: 'weekly_grid_ready is management draft-only. Teacher sees only own published events; Viewer sees only the contract-approved published read-only projection.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'ScheduleEventEditorModalSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['empty', 'error', 'forbidden', 'contract_pending'],
    contractStateCoverage: ['weekly_grid_ready', 'version_mismatch', 'version_required'],
    displays: [
      'Teacher selector placeholder',
      'StudentGroup selector placeholder',
      'Course selector placeholder',
      'Room selector placeholder',
      'TimeSlot selector placeholder',
      'If-Match dependency notice',
      ...OPERATIONS_SAFE_DISPLAY_FIELDS,
    ],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: SCHEDULE_CONTRACT_DEPENDENCIES,
    roleBoundaryNote: 'Create/update/delete controls are management-only placeholders and remain disabled; published and unpublished events are immutable.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'ScheduleConflictPanelSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['empty', 'error', 'forbidden', 'contract_pending'],
    contractStateCoverage: ['validation_invalid', 'validation_stale', 'publish_blocked_hard_conflicts'],
    displays: [
      'hard conflict count placeholder',
      'teacher overlap group placeholder',
      'StudentGroup overlap group placeholder',
      'Room overlap group placeholder',
      'validation version placeholder',
      ...OPERATIONS_SAFE_DISPLAY_FIELDS,
    ],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: SCHEDULE_CONTRACT_DEPENDENCIES,
    roleBoundaryNote: 'Conflict read is management-only pending Permission Catalog; conflict details must remain allowlisted and role-safe.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'ScheduleValidationResultSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['loading', 'empty', 'error', 'forbidden', 'contract_pending'],
    contractStateCoverage: [
      'validation_not_validated',
      'validation_valid',
      'validation_invalid',
      'validation_stale',
    ],
    displays: [
      'validation status placeholder',
      'hard conflict count placeholder',
      'can publish placeholder',
      'validated schedule version placeholder',
      'validated-at placeholder',
      ...OPERATIONS_SAFE_DISPLAY_FIELDS,
    ],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: SCHEDULE_CONTRACT_DEPENDENCIES,
    roleBoundaryNote: 'Only full validation on the current version can satisfy the publish gate; affected validation never enables publish.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'SchedulePublishConfirmationSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['empty', 'error', 'forbidden', 'contract_pending'],
    contractStateCoverage: [
      'publish_confirmation',
      'publish_blocked_empty',
      'publish_blocked_validation_stale',
      'publish_blocked_hard_conflicts',
      'publish_blocked_period_conflict',
      'version_mismatch',
    ],
    displays: [
      'draft status condition',
      'event count condition',
      'current full validation condition',
      'hard conflict zero condition',
      'published period conflict condition',
      'distinct reason-code placeholder',
      'PII-free note placeholder',
      ...OPERATIONS_SAFE_DISPLAY_FIELDS,
    ],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: SCHEDULE_CONTRACT_DEPENDENCIES,
    roleBoundaryNote: 'Publish and unpublish are management-only placeholders; each blocked outcome preserves its contract reason code and no confirmation action is enabled.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'ScheduleStaleVersionWarningSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['error', 'contract_pending'],
    contractStateCoverage: ['validation_stale', 'publish_blocked_validation_stale', 'version_mismatch', 'version_required'],
    displays: [
      'stale version warning',
      'reload-required notice',
      'local mutation not applied notice',
      'ETag and If-Match contract notice',
      ...OPERATIONS_SAFE_DISPLAY_FIELDS,
    ],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: SCHEDULE_CONTRACT_DEPENDENCIES,
    roleBoundaryNote: 'No automatic retry, merge or mutation is attempted after 412, 422 stale-validation or 428 contract states.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'ScheduleForbiddenStateSkeleton',
    module: 'schedule',
    route: '/app/schedule',
    stateCoverage: ['forbidden'],
    contractStateCoverage: [],
    displays: ['403 reason placeholder', 'safe navigation placeholder', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: ['403 reason mapping', 'own-scope violation contract', 'tenant context contract'],
    roleBoundaryNote: 'Teacher draft/conflict/publish attempts and cross-scope requests resolve to safe 403 descriptors without existence disclosure.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'AttendanceOverviewPageSkeleton',
    module: 'attendance',
    route: '/app/attendance',
    stateCoverage: ['loading', 'empty', 'error', 'forbidden', 'contract_pending'],
    displays: ['session count placeholder', 'missing-attendance placeholder', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: ['published schedule to attendance-session generation contract', 'attendance API contract'],
    roleBoundaryNote: 'Viewer hidden; Teacher own-read only. M3 does not generate AttendanceSession in this frontend slice.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'AttendanceSessionPageSkeleton',
    module: 'attendance',
    route: '/app/attendance/session/:sessionId',
    stateCoverage: ['loading', 'empty', 'error', 'forbidden', 'contract_pending'],
    displays: ['session metadata placeholder', 'PII-free roster boundary notice', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: ['attendance session lifecycle', 'student roster minimum-field policy'],
    roleBoundaryNote: 'Teacher own-read placeholder only; submit remains disabled until Attendance contract approval.',
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
  {
    name: 'AttendancePiiSafeEmptyState',
    module: 'attendance',
    route: '/app/attendance/session/:sessionId',
    stateCoverage: ['empty', 'forbidden', 'contract_pending'],
    displays: ['no student data message', ...OPERATIONS_SAFE_DISPLAY_FIELDS],
    doesNotDisplay: OPERATIONS_FUTURE_RENDER_BLOCKLIST,
    contractDependencies: ['student roster minimum-field policy'],
    apiBinding: 'not_connected',
    permissionBinding: 'pending_catalog',
    interactionEnabled: false,
    submitEnabled: false,
    runtimeComponent: false,
  },
] as const;
